// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as PgTypes } from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'c970b619fd071ed7e68d4f6e96af540a298e4e687aaa7a84ab240e59a188651c'>;
export type ExecutionHash =
  ExecutionHashBase<'1984859b211d0748f24576f92cafdb5fb136a35804bdd45239a7ba7eea8dce29'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AreaOfInterest: {
      readonly area: CodecTypes['pg/float8@1']['output'];
      readonly centerLat: CodecTypes['pg/float8@1']['output'];
      readonly centerLon: CodecTypes['pg/float8@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly geometry: CodecTypes['pg/json@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
    };
    readonly Organization: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Product: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly fileSize: CodecTypes['pg/int8@1']['output'];
      readonly format: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly metadata: CodecTypes['pg/json@1']['output'];
      readonly s3Bucket: CodecTypes['pg/text@1']['output'];
      readonly s3Key: CodecTypes['pg/text@1']['output'];
      readonly status: 'PROCESSING' | 'READY' | 'DELIVERED' | 'FAILED';
      readonly thumbnailUrl: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Satellite: {
      readonly capabilities: CodecTypes['pg/json@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly noradId: CodecTypes['pg/int4@1']['output'];
      readonly status: 'ACTIVE' | 'MAINTENANCE' | 'DECOMMISSIONED';
      readonly tle: CodecTypes['pg/json@1']['output'];
      readonly tleUpdatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly SatellitePass: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly direction: CodecTypes['pg/text@1']['output'];
      readonly endTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly footprint: CodecTypes['pg/json@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly maxElevation: CodecTypes['pg/float8@1']['output'];
      readonly satelliteId: CodecTypes['pg/text@1']['output'];
      readonly startTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Task: {
      readonly actualDelivery: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly aoiId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly estimatedDelivery: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lookDirection: 'LEFT' | 'RIGHT';
      readonly organizationId: CodecTypes['pg/text@1']['output'] | null;
      readonly polarization: 'HH' | 'VV' | 'HV' | 'VH';
      readonly priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
      readonly productId: CodecTypes['pg/text@1']['output'] | null;
      readonly requestedEnd: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly requestedStart: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly resolution: 'SPOTLIGHT' | 'STRIPMAP' | 'SCANSAR';
      readonly scheduledPassId: CodecTypes['pg/text@1']['output'] | null;
      readonly status:
        | 'PENDING'
        | 'VALIDATING'
        | 'SCHEDULED'
        | 'ACQUIRING'
        | 'PROCESSING'
        | 'COMPLETED'
        | 'FAILED'
        | 'CANCELLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly validationErrors: CodecTypes['pg/json@1']['output'] | null;
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly organizationId: CodecTypes['pg/text@1']['output'] | null;
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly role: 'USER' | 'ADMIN' | 'OPERATOR';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AreaOfInterest: {
      readonly area: CodecTypes['pg/float8@1']['input'];
      readonly centerLat: CodecTypes['pg/float8@1']['input'];
      readonly centerLon: CodecTypes['pg/float8@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly geometry: CodecTypes['pg/json@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
    };
    readonly Organization: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Product: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly fileSize: CodecTypes['pg/int8@1']['input'];
      readonly format: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly metadata: CodecTypes['pg/json@1']['input'];
      readonly s3Bucket: CodecTypes['pg/text@1']['input'];
      readonly s3Key: CodecTypes['pg/text@1']['input'];
      readonly status: 'PROCESSING' | 'READY' | 'DELIVERED' | 'FAILED';
      readonly thumbnailUrl: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Satellite: {
      readonly capabilities: CodecTypes['pg/json@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly noradId: CodecTypes['pg/int4@1']['input'];
      readonly status: 'ACTIVE' | 'MAINTENANCE' | 'DECOMMISSIONED';
      readonly tle: CodecTypes['pg/json@1']['input'];
      readonly tleUpdatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly SatellitePass: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly direction: CodecTypes['pg/text@1']['input'];
      readonly endTime: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly footprint: CodecTypes['pg/json@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly maxElevation: CodecTypes['pg/float8@1']['input'];
      readonly satelliteId: CodecTypes['pg/text@1']['input'];
      readonly startTime: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Task: {
      readonly actualDelivery: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly aoiId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly estimatedDelivery: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lookDirection: 'LEFT' | 'RIGHT';
      readonly organizationId: CodecTypes['pg/text@1']['input'] | null;
      readonly polarization: 'HH' | 'VV' | 'HV' | 'VH';
      readonly priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
      readonly productId: CodecTypes['pg/text@1']['input'] | null;
      readonly requestedEnd: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly requestedStart: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly resolution: 'SPOTLIGHT' | 'STRIPMAP' | 'SCANSAR';
      readonly scheduledPassId: CodecTypes['pg/text@1']['input'] | null;
      readonly status:
        | 'PENDING'
        | 'VALIDATING'
        | 'SCHEDULED'
        | 'ACQUIRING'
        | 'PROCESSING'
        | 'COMPLETED'
        | 'FAILED'
        | 'CANCELLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly validationErrors: CodecTypes['pg/json@1']['input'] | null;
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly organizationId: CodecTypes['pg/text@1']['input'] | null;
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly role: 'USER' | 'ADMIN' | 'OPERATOR';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly areas_of_interest: {
      readonly area: CodecTypes['pg/float8@1']['output'];
      readonly centerLat: CodecTypes['pg/float8@1']['output'];
      readonly centerLon: CodecTypes['pg/float8@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly geometry: CodecTypes['pg/json@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
    };
    readonly organizations: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly products: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly fileSize: CodecTypes['pg/int8@1']['output'];
      readonly format: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly metadata: CodecTypes['pg/json@1']['output'];
      readonly s3Bucket: CodecTypes['pg/text@1']['output'];
      readonly s3Key: CodecTypes['pg/text@1']['output'];
      readonly status: 'PROCESSING' | 'READY' | 'DELIVERED' | 'FAILED';
      readonly thumbnailUrl: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly satellite_passes: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly direction: CodecTypes['pg/text@1']['output'];
      readonly endTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly footprint: CodecTypes['pg/json@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly maxElevation: CodecTypes['pg/float8@1']['output'];
      readonly satelliteId: CodecTypes['pg/text@1']['output'];
      readonly startTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly satellites: {
      readonly capabilities: CodecTypes['pg/json@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly noradId: CodecTypes['pg/int4@1']['output'];
      readonly status: 'ACTIVE' | 'MAINTENANCE' | 'DECOMMISSIONED';
      readonly tle: CodecTypes['pg/json@1']['output'];
      readonly tleUpdatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly tasks: {
      readonly actualDelivery: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly aoiId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly estimatedDelivery: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lookDirection: 'LEFT' | 'RIGHT';
      readonly organizationId: CodecTypes['pg/text@1']['output'] | null;
      readonly polarization: 'HH' | 'VV' | 'HV' | 'VH';
      readonly priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
      readonly productId: CodecTypes['pg/text@1']['output'] | null;
      readonly requestedEnd: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly requestedStart: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly resolution: 'SPOTLIGHT' | 'STRIPMAP' | 'SCANSAR';
      readonly scheduledPassId: CodecTypes['pg/text@1']['output'] | null;
      readonly status:
        | 'PENDING'
        | 'VALIDATING'
        | 'SCHEDULED'
        | 'ACQUIRING'
        | 'PROCESSING'
        | 'COMPLETED'
        | 'FAILED'
        | 'CANCELLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly validationErrors: CodecTypes['pg/json@1']['output'] | null;
    };
    readonly users: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly organizationId: CodecTypes['pg/text@1']['output'] | null;
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly role: 'USER' | 'ADMIN' | 'OPERATOR';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly areas_of_interest: {
      readonly area: CodecTypes['pg/float8@1']['input'];
      readonly centerLat: CodecTypes['pg/float8@1']['input'];
      readonly centerLon: CodecTypes['pg/float8@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly geometry: CodecTypes['pg/json@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
    };
    readonly organizations: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly products: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly fileSize: CodecTypes['pg/int8@1']['input'];
      readonly format: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly metadata: CodecTypes['pg/json@1']['input'];
      readonly s3Bucket: CodecTypes['pg/text@1']['input'];
      readonly s3Key: CodecTypes['pg/text@1']['input'];
      readonly status: 'PROCESSING' | 'READY' | 'DELIVERED' | 'FAILED';
      readonly thumbnailUrl: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly satellite_passes: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly direction: CodecTypes['pg/text@1']['input'];
      readonly endTime: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly footprint: CodecTypes['pg/json@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly maxElevation: CodecTypes['pg/float8@1']['input'];
      readonly satelliteId: CodecTypes['pg/text@1']['input'];
      readonly startTime: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly satellites: {
      readonly capabilities: CodecTypes['pg/json@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly noradId: CodecTypes['pg/int4@1']['input'];
      readonly status: 'ACTIVE' | 'MAINTENANCE' | 'DECOMMISSIONED';
      readonly tle: CodecTypes['pg/json@1']['input'];
      readonly tleUpdatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly tasks: {
      readonly actualDelivery: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly aoiId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly estimatedDelivery: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lookDirection: 'LEFT' | 'RIGHT';
      readonly organizationId: CodecTypes['pg/text@1']['input'] | null;
      readonly polarization: 'HH' | 'VV' | 'HV' | 'VH';
      readonly priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
      readonly productId: CodecTypes['pg/text@1']['input'] | null;
      readonly requestedEnd: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly requestedStart: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly resolution: 'SPOTLIGHT' | 'STRIPMAP' | 'SCANSAR';
      readonly scheduledPassId: CodecTypes['pg/text@1']['input'] | null;
      readonly status:
        | 'PENDING'
        | 'VALIDATING'
        | 'SCHEDULED'
        | 'ACQUIRING'
        | 'PROCESSING'
        | 'COMPLETED'
        | 'FAILED'
        | 'CANCELLED';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly validationErrors: CodecTypes['pg/json@1']['input'] | null;
    };
    readonly users: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly organizationId: CodecTypes['pg/text@1']['input'] | null;
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly role: 'USER' | 'ADMIN' | 'OPERATOR';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};

export namespace Models {
  export type public_AreaOfInterest = {
    area: CodecTypes['pg/float8@1']['output'];
    centerLat: CodecTypes['pg/float8@1']['output'];
    centerLon: CodecTypes['pg/float8@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    geometry: CodecTypes['pg/json@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    tasks: public_Task[];
    readonly [RelationKeys]?: 'tasks';
  };
  export type public_Organization = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    tasks: public_Task[];
    users: public_User[];
    readonly [RelationKeys]?: 'tasks' | 'users';
  };
  export type public_Product = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    deliveredAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    fileSize: CodecTypes['pg/int8@1']['output'];
    format: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    metadata: CodecTypes['pg/json@1']['output'];
    s3Bucket: CodecTypes['pg/text@1']['output'];
    s3Key: CodecTypes['pg/text@1']['output'];
    status: 'PROCESSING' | 'READY' | 'DELIVERED' | 'FAILED';
    thumbnailUrl: CodecTypes['pg/text@1']['output'] | null;
    task: public_Task | null;
    readonly [RelationKeys]?: 'task';
  };
  export type public_Satellite = {
    capabilities: CodecTypes['pg/json@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    noradId: CodecTypes['pg/int4@1']['output'];
    status: 'ACTIVE' | 'MAINTENANCE' | 'DECOMMISSIONED';
    tle: CodecTypes['pg/json@1']['output'];
    tleUpdatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    passes: public_SatellitePass[];
    readonly [RelationKeys]?: 'passes';
  };
  export type public_SatellitePass = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    direction: CodecTypes['pg/text@1']['output'];
    endTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
    footprint: CodecTypes['pg/json@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    maxElevation: CodecTypes['pg/float8@1']['output'];
    satelliteId: CodecTypes['pg/text@1']['output'];
    startTime: CodecTypes['pg/timestamptz-temporal@1']['output'];
    satellite: public_Satellite;
    task: public_Task | null;
    readonly [RelationKeys]?: 'satellite' | 'task';
  };
  export type public_Task = {
    actualDelivery: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    aoiId: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    estimatedDelivery: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    lookDirection: 'LEFT' | 'RIGHT';
    organizationId: CodecTypes['pg/text@1']['output'] | null;
    polarization: 'HH' | 'VV' | 'HV' | 'VH';
    priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
    productId: CodecTypes['pg/text@1']['output'] | null;
    requestedEnd: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    requestedStart: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    resolution: 'SPOTLIGHT' | 'STRIPMAP' | 'SCANSAR';
    scheduledPassId: CodecTypes['pg/text@1']['output'] | null;
    status:
      | 'PENDING'
      | 'VALIDATING'
      | 'SCHEDULED'
      | 'ACQUIRING'
      | 'PROCESSING'
      | 'COMPLETED'
      | 'FAILED'
      | 'CANCELLED';
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    userId: CodecTypes['pg/text@1']['output'];
    validationErrors: CodecTypes['pg/json@1']['output'] | null;
    aoi: public_AreaOfInterest;
    organization: public_Organization | null;
    product: public_Product | null;
    scheduledPass: public_SatellitePass | null;
    user: public_User;
    readonly [RelationKeys]?: 'aoi' | 'organization' | 'product' | 'scheduledPass' | 'user';
  };
  export type public_User = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    organizationId: CodecTypes['pg/text@1']['output'] | null;
    passwordHash: CodecTypes['pg/text@1']['output'];
    role: 'USER' | 'ADMIN' | 'OPERATOR';
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    organization: public_Organization | null;
    tasks: public_Task[];
    readonly [RelationKeys]?: 'organization' | 'tasks';
  };
}

export declare const models: {
  public: {
    AreaOfInterest: Models.public_AreaOfInterest;
    Organization: Models.public_Organization;
    Product: Models.public_Product;
    Satellite: Models.public_Satellite;
    SatellitePass: Models.public_SatellitePass;
    Task: Models.public_Task;
    User: Models.public_User;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly areas_of_interest: {
              columns: {
                readonly area: {
                  readonly dataType: 'pg/float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly centerLat: {
                  readonly dataType: 'pg/float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly centerLon: {
                  readonly dataType: 'pg/float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly geometry: {
                  readonly dataType: 'pg/json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'areas_of_interest_centerLat_centerLon_idx_9cc9dd2c';
                  readonly prefix: 'areas_of_interest_centerLat_centerLon_idx';
                  readonly columns: readonly ['centerLat', 'centerLon'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly organizations: {
              columns: {
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly name: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly products: {
              columns: {
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly deliveredAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly fileSize: {
                  readonly dataType: 'pg/int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly format: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly metadata: {
                  readonly dataType: 'pg/json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly s3Bucket: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly s3Key: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly status: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PROCESSING'>;
                  };
                  readonly many: false;
                };
                readonly thumbnailUrl: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'products_status_idx_e98638ab';
                  readonly prefix: 'products_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly satellite_passes: {
              columns: {
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly direction: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly endTime: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly footprint: {
                  readonly dataType: 'pg/json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly maxElevation: {
                  readonly dataType: 'pg/float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly satelliteId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly startTime: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'satellite_passes_satelliteId_idx_e4580212';
                  readonly prefix: 'satellite_passes_satelliteId_idx';
                  readonly columns: readonly ['satelliteId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'satellite_passes_satelliteId_startTime_idx_0042055b';
                  readonly prefix: 'satellite_passes_satelliteId_startTime_idx';
                  readonly columns: readonly ['satelliteId', 'startTime'];
                  readonly unique: false;
                },
                {
                  readonly name: 'satellite_passes_startTime_endTime_idx_d8ca590d';
                  readonly prefix: 'satellite_passes_startTime_endTime_idx';
                  readonly columns: readonly ['startTime', 'endTime'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'satellite_passes';
                    readonly columns: readonly ['satelliteId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'satellites';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly satellites: {
              columns: {
                readonly capabilities: {
                  readonly dataType: 'pg/json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly name: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly noradId: {
                  readonly dataType: 'pg/int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly status: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'ACTIVE'>;
                  };
                  readonly many: false;
                };
                readonly tle: {
                  readonly dataType: 'pg/json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly tleUpdatedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly updatedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['name'] },
                { readonly columns: readonly ['noradId'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'satellites_status_idx_e98638ab';
                  readonly prefix: 'satellites_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly tasks: {
              columns: {
                readonly actualDelivery: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly aoiId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly estimatedDelivery: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly lookDirection: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'RIGHT'>;
                  };
                  readonly many: false;
                };
                readonly organizationId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly polarization: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly priority: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'MEDIUM'>;
                  };
                  readonly many: false;
                };
                readonly productId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly requestedEnd: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly requestedStart: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly resolution: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly scheduledPassId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly status: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                  readonly many: false;
                };
                readonly updatedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly userId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly validationErrors: {
                  readonly dataType: 'pg/json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: true;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['scheduledPassId'] },
                { readonly columns: readonly ['productId'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'tasks_aoiId_idx_efb8e51f';
                  readonly prefix: 'tasks_aoiId_idx';
                  readonly columns: readonly ['aoiId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'tasks_createdAt_idx_9575dbd7';
                  readonly prefix: 'tasks_createdAt_idx';
                  readonly columns: readonly ['createdAt'];
                  readonly unique: false;
                },
                {
                  readonly name: 'tasks_organizationId_idx_2e17ef41';
                  readonly prefix: 'tasks_organizationId_idx';
                  readonly columns: readonly ['organizationId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'tasks_status_idx_e98638ab';
                  readonly prefix: 'tasks_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
                {
                  readonly name: 'tasks_userId_idx_a489d58a';
                  readonly prefix: 'tasks_userId_idx';
                  readonly columns: readonly ['userId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tasks';
                    readonly columns: readonly ['userId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tasks';
                    readonly columns: readonly ['organizationId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'organizations';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tasks';
                    readonly columns: readonly ['aoiId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'areas_of_interest';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tasks';
                    readonly columns: readonly ['scheduledPassId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'satellite_passes';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'tasks';
                    readonly columns: readonly ['productId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'products';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly users: {
              columns: {
                readonly createdAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly email: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly name: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly organizationId: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly passwordHash: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly role: {
                  readonly dataType: 'pg/text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'USER'>;
                  };
                  readonly many: false;
                };
                readonly updatedAt: {
                  readonly dataType: 'pg/timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [
                {
                  readonly name: 'users_email_idx_46df9cad';
                  readonly prefix: 'users_email_idx';
                  readonly columns: readonly ['email'];
                  readonly unique: false;
                },
                {
                  readonly name: 'users_organizationId_idx_2e17ef41';
                  readonly prefix: 'users_organizationId_idx';
                  readonly columns: readonly ['organizationId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['organizationId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'organizations';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly LookDirection: {
              readonly kind: 'valueSet';
              readonly values: readonly ['LEFT', 'RIGHT'];
            };
            readonly Polarization: {
              readonly kind: 'valueSet';
              readonly values: readonly ['HH', 'VV', 'HV', 'VH'];
            };
            readonly Priority: {
              readonly kind: 'valueSet';
              readonly values: readonly ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
            };
            readonly ProductStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PROCESSING', 'READY', 'DELIVERED', 'FAILED'];
            };
            readonly ResolutionMode: {
              readonly kind: 'valueSet';
              readonly values: readonly ['SPOTLIGHT', 'STRIPMAP', 'SCANSAR'];
            };
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['USER', 'ADMIN', 'OPERATOR'];
            };
            readonly SatelliteStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ACTIVE', 'MAINTENANCE', 'DECOMMISSIONED'];
            };
            readonly TaskStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'PENDING',
                'VALIDATING',
                'SCHEDULED',
                'ACQUIRING',
                'PROCESSING',
                'COMPLETED',
                'FAILED',
                'CANCELLED',
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly areas_of_interest: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AreaOfInterest';
    };
    readonly organizations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Organization';
    };
    readonly products: { readonly namespace: 'public' & NamespaceId; readonly model: 'Product' };
    readonly satellite_passes: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SatellitePass';
    };
    readonly satellites: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Satellite';
    };
    readonly tasks: { readonly namespace: 'public' & NamespaceId; readonly model: 'Task' };
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AreaOfInterest: {
            readonly fields: {
              readonly area: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly centerLat: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly centerLon: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly geometry: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly tasks: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Task' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['aoiId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'areas_of_interest';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly area: { readonly column: 'area' };
                readonly centerLat: { readonly column: 'centerLat' };
                readonly centerLon: { readonly column: 'centerLon' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly geometry: { readonly column: 'geometry' };
                readonly id: { readonly column: 'id' };
              };
            };
          };
          readonly Organization: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly tasks: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Task' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['organizationId'];
                };
              };
              readonly users: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['organizationId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'organizations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Product: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly deliveredAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly fileSize: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
              readonly format: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly metadata: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly s3Bucket: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly s3Key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly thumbnailUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly task: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Task' };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['productId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'products';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly deliveredAt: { readonly column: 'deliveredAt' };
                readonly fileSize: { readonly column: 'fileSize' };
                readonly format: { readonly column: 'format' };
                readonly id: { readonly column: 'id' };
                readonly metadata: { readonly column: 'metadata' };
                readonly s3Bucket: { readonly column: 's3Bucket' };
                readonly s3Key: { readonly column: 's3Key' };
                readonly status: { readonly column: 'status' };
                readonly thumbnailUrl: { readonly column: 'thumbnailUrl' };
              };
            };
          };
          readonly Satellite: {
            readonly fields: {
              readonly capabilities: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly noradId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tle: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly tleUpdatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly passes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SatellitePass';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['satelliteId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'satellites';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly capabilities: { readonly column: 'capabilities' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly noradId: { readonly column: 'noradId' };
                readonly status: { readonly column: 'status' };
                readonly tle: { readonly column: 'tle' };
                readonly tleUpdatedAt: { readonly column: 'tleUpdatedAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly SatellitePass: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly direction: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly endTime: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly footprint: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly maxElevation: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly satelliteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startTime: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly satellite: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Satellite';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['satelliteId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly task: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Task' };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['scheduledPassId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'satellite_passes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly direction: { readonly column: 'direction' };
                readonly endTime: { readonly column: 'endTime' };
                readonly footprint: { readonly column: 'footprint' };
                readonly id: { readonly column: 'id' };
                readonly maxElevation: { readonly column: 'maxElevation' };
                readonly satelliteId: { readonly column: 'satelliteId' };
                readonly startTime: { readonly column: 'startTime' };
              };
            };
          };
          readonly Task: {
            readonly fields: {
              readonly actualDelivery: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly aoiId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly estimatedDelivery: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lookDirection: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly organizationId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly polarization: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly priority: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly productId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly requestedEnd: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly requestedStart: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly resolution: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly scheduledPassId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly validationErrors: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
            };
            readonly relations: {
              readonly aoi: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AreaOfInterest';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['aoiId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly organization: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Organization';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['organizationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly product: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['productId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly scheduledPass: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SatellitePass';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['scheduledPassId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tasks';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly actualDelivery: { readonly column: 'actualDelivery' };
                readonly aoiId: { readonly column: 'aoiId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly estimatedDelivery: { readonly column: 'estimatedDelivery' };
                readonly id: { readonly column: 'id' };
                readonly lookDirection: { readonly column: 'lookDirection' };
                readonly organizationId: { readonly column: 'organizationId' };
                readonly polarization: { readonly column: 'polarization' };
                readonly priority: { readonly column: 'priority' };
                readonly productId: { readonly column: 'productId' };
                readonly requestedEnd: { readonly column: 'requestedEnd' };
                readonly requestedStart: { readonly column: 'requestedStart' };
                readonly resolution: { readonly column: 'resolution' };
                readonly scheduledPassId: { readonly column: 'scheduledPassId' };
                readonly status: { readonly column: 'status' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly userId: { readonly column: 'userId' };
                readonly validationErrors: { readonly column: 'validationErrors' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly organizationId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly organization: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Organization';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['organizationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly tasks: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'Task' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly organizationId: { readonly column: 'organizationId' };
                readonly passwordHash: { readonly column: 'passwordHash' };
                readonly role: { readonly column: 'role' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly LookDirection: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'LEFT'; readonly value: 'LEFT' },
              { readonly name: 'RIGHT'; readonly value: 'RIGHT' },
            ];
          };
          readonly Polarization: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'HH'; readonly value: 'HH' },
              { readonly name: 'VV'; readonly value: 'VV' },
              { readonly name: 'HV'; readonly value: 'HV' },
              { readonly name: 'VH'; readonly value: 'VH' },
            ];
          };
          readonly Priority: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'LOW'; readonly value: 'LOW' },
              { readonly name: 'MEDIUM'; readonly value: 'MEDIUM' },
              { readonly name: 'HIGH'; readonly value: 'HIGH' },
              { readonly name: 'URGENT'; readonly value: 'URGENT' },
            ];
          };
          readonly ProductStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PROCESSING'; readonly value: 'PROCESSING' },
              { readonly name: 'READY'; readonly value: 'READY' },
              { readonly name: 'DELIVERED'; readonly value: 'DELIVERED' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
            ];
          };
          readonly ResolutionMode: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'SPOTLIGHT'; readonly value: 'SPOTLIGHT' },
              { readonly name: 'STRIPMAP'; readonly value: 'STRIPMAP' },
              { readonly name: 'SCANSAR'; readonly value: 'SCANSAR' },
            ];
          };
          readonly Role: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'USER'; readonly value: 'USER' },
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
              { readonly name: 'OPERATOR'; readonly value: 'OPERATOR' },
            ];
          };
          readonly SatelliteStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ACTIVE'; readonly value: 'ACTIVE' },
              { readonly name: 'MAINTENANCE'; readonly value: 'MAINTENANCE' },
              { readonly name: 'DECOMMISSIONED'; readonly value: 'DECOMMISSIONED' },
            ];
          };
          readonly TaskStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'VALIDATING'; readonly value: 'VALIDATING' },
              { readonly name: 'SCHEDULED'; readonly value: 'SCHEDULED' },
              { readonly name: 'ACQUIRING'; readonly value: 'ACQUIRING' },
              { readonly name: 'PROCESSING'; readonly value: 'PROCESSING' },
              { readonly name: 'COMPLETED'; readonly value: 'COMPLETED' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly forKeyShare: true;
      readonly forNoKeyUpdate: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly forShare: true;
      readonly forUpdate: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly lockNowait: true;
      readonly lockOf: true;
      readonly lockSkipLocked: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'areas_of_interest';
            readonly field: 'createdAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'areas_of_interest';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'organizations';
            readonly field: 'createdAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'organizations';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'products';
            readonly field: 'createdAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'products';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'satellite_passes';
            readonly field: 'createdAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'satellite_passes';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'satellites';
            readonly field: 'createdAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'satellites';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'satellites';
            readonly field: 'updatedAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'tasks';
            readonly field: 'createdAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'tasks';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'tasks';
            readonly field: 'updatedAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'users';
            readonly field: 'createdAt';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'users';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'users';
            readonly field: 'updatedAt';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
